### ISSUE TITLE
Clarification on the -n Argument

### ISSUE THREAD

**Issue by alixaxel** [louridas/pagerank#6]
Hi, I'm experimenting with the binary but the description in the README for `-n` is somewhat confusing:

> -n: if set, the graph_file is in numeric format, that is it consists of lines of the form where and are integer vertex indices, starting with zero. If not set, the graph_file consists of lines of the form where and and vertex IDs, and will be interpreted as strings.

Could you please clarify / improve it's description? :)

**Comment by alixaxel** [comment]
@louridas Awesome, much clearer now. You might just want to change and to are in:

> where `<from>` and `<to>` and vertex 

Thanks for making this OSS btw, great stuff.

**Comment by louridas** [comment]
Thanks again, fixed!
